"""
커리큘럼 카탈로그 — 단일 소스 오브 트루스
chapter.py (학습 콘텐츠 생성) + progress.py (로드맵 API) 모두 여기서 import
"""

CURRICULUM_CATALOG: dict[str, dict] = {
    "rag": {
        "title": "RAG (검색 증강 생성)",
        "emoji": "🔍",
        "color": "#10B981",
        "description": "AI가 외부 지식을 검색해서 답하는 기술",
        "topic_names": ["RAG"],
        "chapters": [
            {"id": "rag-1", "title": "검색이란 무엇인가?",
             "description": "정보를 찾는 방법 — 키워드 검색부터 의미 검색까지",
             "level": "입문", "duration": "5분",
             "concepts": ["키워드 검색", "의미 검색", "TF-IDF"]},
            {"id": "rag-2", "title": "임베딩과 벡터 DB",
             "description": "텍스트를 숫자로 바꾸면 뭐가 달라질까?",
             "level": "기본", "duration": "7분",
             "concepts": ["임베딩", "벡터 DB", "코사인 유사도"]},
            {"id": "rag-3", "title": "Chunking 전략",
             "description": "긴 문서를 어떻게 잘라야 AI가 잘 이해할까?",
             "level": "기본", "duration": "6분",
             "concepts": ["Chunking", "Overlap", "토큰 길이"]},
            {"id": "rag-4", "title": "고급 RAG 기법 (HyDE, Re-ranking)",
             "description": "검색 정확도를 더 높이는 방법들",
             "level": "심화", "duration": "10분",
             "concepts": ["HyDE", "Re-ranking", "Self-RAG"]},
            {"id": "rag-5", "title": "실전 RAG 파이프라인 구축",
             "description": "처음부터 끝까지 직접 만들어보기",
             "level": "심화", "duration": "15분",
             "concepts": ["파이프라인", "평가 지표", "레이턴시"]},
            {"id": "rag-6", "title": "Hybrid Search",
             "description": "키워드 검색과 벡터 검색을 합치면 어떻게 될까?",
             "level": "심화", "duration": "8분",
             "concepts": ["BM25", "하이브리드 검색", "RRF(Reciprocal Rank Fusion)"]},
            {"id": "rag-7", "title": "멀티모달 RAG",
             "description": "이미지·표·PDF까지 검색하는 RAG",
             "level": "심화", "duration": "10분",
             "concepts": ["이미지 임베딩", "표 파싱", "멀티모달 모델"]},
            {"id": "rag-8", "title": "Graph RAG",
             "description": "지식 그래프로 관계 기반 검색하기",
             "level": "심화", "duration": "10분",
             "concepts": ["지식 그래프", "엔티티", "그래프 DB"]},
            {"id": "rag-9", "title": "RAG 평가 프레임워크",
             "description": "내 RAG가 잘 작동하는지 어떻게 알까?",
             "level": "심화", "duration": "9분",
             "concepts": ["RAGAS", "정밀도", "재현율", "충실도"]},
            {"id": "rag-10", "title": "프로덕션 RAG 운영",
             "description": "실서비스에서 비용·속도·품질 균형 잡기",
             "level": "심화", "duration": "12분",
             "concepts": ["캐싱", "모니터링", "비용 최적화", "A/B 테스트"]},
        ],
    },
    "agent": {
        "title": "Agentic AI",
        "emoji": "🤖",
        "color": "#8B5CF6",
        "description": "스스로 생각하고 도구를 사용하는 AI",
        "topic_names": ["Agentic AI"],
        "chapters": [
            {"id": "agent-1", "title": "Agent란 무엇인가?",
             "description": "단순 AI와 Agent의 차이, ReAct 패턴 이해",
             "level": "입문", "duration": "5분",
             "concepts": ["Agent", "ReAct", "Tool Use"]},
            {"id": "agent-2", "title": "도구 사용 (Tool Use)",
             "description": "AI가 계산기, 검색, 코드를 직접 실행한다면?",
             "level": "기본", "duration": "7분",
             "concepts": ["Function Calling", "Tool", "API 연동"]},
            {"id": "agent-3", "title": "멀티 에이전트 시스템",
             "description": "여러 AI가 협력해서 문제를 푸는 방법",
             "level": "기본", "duration": "8분",
             "concepts": ["Multi-Agent", "오케스트레이터", "서브에이전트"]},
            {"id": "agent-4", "title": "메모리와 상태 관리",
             "description": "Agent가 대화를 기억하고 학습하는 방법",
             "level": "심화", "duration": "10분",
             "concepts": ["단기 기억", "장기 기억", "벡터 메모리"]},
            {"id": "agent-5", "title": "실전 Agent 배포",
             "description": "내 Agent를 실제 서비스로 만들기",
             "level": "심화", "duration": "15분",
             "concepts": ["배포", "모니터링", "비용 최적화"]},
            {"id": "agent-6", "title": "계획 수립 — Tree of Thought",
             "description": "AI가 여러 경로를 탐색해 최선을 고르는 방법",
             "level": "심화", "duration": "9분",
             "concepts": ["Tree of Thought", "Chain of Thought", "MCTS"]},
            {"id": "agent-7", "title": "코드 실행 Agent",
             "description": "Code Interpreter — AI가 직접 코드를 짜고 실행한다면?",
             "level": "심화", "duration": "10분",
             "concepts": ["Code Interpreter", "샌드박스", "자동 디버깅"]},
            {"id": "agent-8", "title": "Web/Browser Agent",
             "description": "AI가 인터넷을 직접 탐색하는 방법",
             "level": "심화", "duration": "9분",
             "concepts": ["Browser Use", "스크래핑", "DOM 조작"]},
            {"id": "agent-9", "title": "Agent 오케스트레이션 패턴",
             "description": "Supervisor, Swarm — 에이전트 팀을 어떻게 짤까?",
             "level": "심화", "duration": "11분",
             "concepts": ["Supervisor", "Swarm", "핸드오프", "워크플로우"]},
            {"id": "agent-10", "title": "Agent 평가와 안전성",
             "description": "Agent가 잘못된 행동을 하면? 평가·제어 방법",
             "level": "심화", "duration": "10분",
             "concepts": ["할루시네이션", "가드레일", "평가 프레임워크"]},
        ],
    },
    "llm": {
        "title": "LLM 기초",
        "emoji": "🧠",
        "color": "#F59E0B",
        "description": "대형 언어 모델의 작동 원리",
        "topic_names": ["LLM 기초"],
        "chapters": [
            {"id": "llm-1", "title": "Transformer 쉽게 이해하기",
             "description": "GPT, Claude는 어떻게 글을 쓸까?",
             "level": "입문", "duration": "8분",
             "concepts": ["Transformer", "Attention", "Self-Attention"]},
            {"id": "llm-2", "title": "프롬프트 엔지니어링",
             "description": "AI에게 잘 부탁하는 방법",
             "level": "기본", "duration": "6분",
             "concepts": ["프롬프트", "Chain-of-Thought", "Few-shot"]},
            {"id": "llm-3", "title": "Fine-tuning vs RAG",
             "description": "언제 학습시키고 언제 검색시킬까?",
             "level": "심화", "duration": "10분",
             "concepts": ["Fine-tuning", "RAG", "LoRA"]},
            {"id": "llm-4", "title": "LLM 평가와 벤치마크",
             "description": "AI 성능을 어떻게 측정할까?",
             "level": "심화", "duration": "8분",
             "concepts": ["MMLU", "HumanEval", "평가 지표"]},
            {"id": "llm-5", "title": "토크나이저와 컨텍스트 윈도우",
             "description": "AI는 글자를 어떻게 쪼개서 읽을까?",
             "level": "기본", "duration": "7분",
             "concepts": ["토큰", "BPE", "컨텍스트 윈도우", "토큰 비용"]},
            {"id": "llm-6", "title": "추론 최적화",
             "description": "LLM을 더 빠르고 저렴하게 쓰는 기술들",
             "level": "심화", "duration": "9분",
             "concepts": ["양자화", "KV 캐시", "스펙큘레이티브 디코딩"]},
            {"id": "llm-7", "title": "LLM 정렬 (RLHF)",
             "description": "AI가 사람의 의도를 따르도록 훈련하는 방법",
             "level": "심화", "duration": "10분",
             "concepts": ["RLHF", "RLAIF", "보상 모델", "Constitutional AI"]},
            {"id": "llm-8", "title": "멀티모달 LLM",
             "description": "이미지·음성·영상을 함께 이해하는 AI",
             "level": "심화", "duration": "9분",
             "concepts": ["멀티모달", "비전 인코더", "크로스 어텐션"]},
            {"id": "llm-9", "title": "오픈소스 LLM 생태계",
             "description": "Llama, Mistral — GPT 없이도 강력한 AI를 쓸 수 있다",
             "level": "심화", "duration": "8분",
             "concepts": ["Llama", "Mistral", "Ollama", "로컬 실행"]},
            {"id": "llm-10", "title": "LLM 보안과 레드팀",
             "description": "프롬프트 인젝션부터 탈옥까지 — AI 공격과 방어",
             "level": "심화", "duration": "10분",
             "concepts": ["프롬프트 인젝션", "탈옥", "레드팀", "안전 정렬"]},
        ],
    },
    "quantum": {
        "title": "양자컴퓨팅",
        "emoji": "⚛️",
        "color": "#06B6D4",
        "description": "미래 컴퓨팅의 혁명, 양자의 세계",
        "topic_names": ["양자컴퓨팅"],
        "chapters": [
            {"id": "quantum-1", "title": "양자역학 기초",
             "description": "중첩과 얽힘 — 고전 물리와 뭐가 다를까?",
             "level": "입문", "duration": "8분",
             "concepts": ["중첩", "얽힘", "파동-입자 이중성"]},
            {"id": "quantum-2", "title": "큐비트와 양자 게이트",
             "description": "0과 1을 동시에 가지는 비트의 세계",
             "level": "기본", "duration": "7분",
             "concepts": ["큐비트", "양자 게이트", "양자 회로"]},
            {"id": "quantum-3", "title": "양자 알고리즘 이해",
             "description": "Shor, Grover — 왜 고전 컴퓨터보다 빠를까?",
             "level": "기본", "duration": "10분",
             "concepts": ["Shor 알고리즘", "Grover 알고리즘", "양자 병렬성"]},
            {"id": "quantum-4", "title": "양자 컴퓨터 현황",
             "description": "IBM, Google의 실제 기기와 한계",
             "level": "심화", "duration": "8분",
             "concepts": ["노이즈", "양자 오류 정정", "NISQ"]},
            {"id": "quantum-5", "title": "양자컴퓨팅의 미래",
             "description": "암호, 신약 개발, AI에 어떻게 쓰일까?",
             "level": "심화", "duration": "10분",
             "concepts": ["양자 암호", "양자 시뮬레이션", "양자 머신러닝"]},
            {"id": "quantum-6", "title": "양자 오류 정정 심화",
             "description": "노이즈를 이겨내는 방법 — 표면 코드란?",
             "level": "심화", "duration": "10분",
             "concepts": ["표면 코드", "논리 큐비트", "임계 오류율"]},
            {"id": "quantum-7", "title": "양자 통신과 암호",
             "description": "절대 도청할 수 없는 통신 — QKD의 원리",
             "level": "심화", "duration": "9분",
             "concepts": ["QKD", "양자 얽힘", "BB84 프로토콜"]},
            {"id": "quantum-8", "title": "양자 화학 시뮬레이션",
             "description": "신약 개발과 재료 과학에 양자가 쓰이는 방법",
             "level": "심화", "duration": "10분",
             "concepts": ["분자 시뮬레이션", "VQE", "해밀토니안"]},
            {"id": "quantum-9", "title": "양자-고전 하이브리드 알고리즘",
             "description": "현재 NISQ 기기에서 실용적으로 쓰는 방법",
             "level": "심화", "duration": "9분",
             "concepts": ["QAOA", "VQE", "변분 알고리즘", "NISQ"]},
            {"id": "quantum-10", "title": "양자 프로그래밍 입문 (Qiskit)",
             "description": "IBM Quantum으로 실제 양자 회로 짜보기",
             "level": "심화", "duration": "12분",
             "concepts": ["Qiskit", "양자 회로", "IBM Quantum", "측정"]},
        ],
    },
    "invest": {
        "title": "주식/투자",
        "emoji": "📈",
        "color": "#EF4444",
        "description": "돈이 일하게 만드는 투자의 원리",
        "topic_names": ["주식/투자", "주식", "투자"],
        "chapters": [
            {"id": "invest-1", "title": "주식이란 무엇인가?",
             "description": "회사 조각을 사는 행위의 의미",
             "level": "입문", "duration": "6분",
             "concepts": ["주식", "시가총액", "주주"]},
            {"id": "invest-2", "title": "재무제표 읽기",
             "description": "PER, PBR, ROE — 숫자로 기업을 이해하는 법",
             "level": "기본", "duration": "8분",
             "concepts": ["PER", "PBR", "ROE", "영업이익"]},
            {"id": "invest-3", "title": "가치 투자 vs 성장 투자",
             "description": "워렌 버핏 vs 피터 린치의 철학",
             "level": "기본", "duration": "7분",
             "concepts": ["가치 투자", "성장 투자", "안전마진"]},
            {"id": "invest-4", "title": "ETF와 분산 투자",
             "description": "달걀을 한 바구니에 담지 않는 법",
             "level": "기본", "duration": "6분",
             "concepts": ["ETF", "분산 투자", "포트폴리오"]},
            {"id": "invest-5", "title": "투자 심리학",
             "description": "공포와 탐욕을 이기는 행동경제학",
             "level": "심화", "duration": "10분",
             "concepts": ["손실 회피", "군중 심리", "장기 투자"]},
            {"id": "invest-6", "title": "기술적 분석 기초",
             "description": "차트로 시장의 흐름을 읽는 법",
             "level": "기본", "duration": "8분",
             "concepts": ["이동평균선", "RSI", "MACD", "지지/저항선"]},
            {"id": "invest-7", "title": "채권과 금리",
             "description": "금리가 오르면 왜 주식이 떨어질까?",
             "level": "기본", "duration": "7분",
             "concepts": ["채권", "금리", "역상관관계", "듀레이션"]},
            {"id": "invest-8", "title": "파생상품 기초",
             "description": "선물, 옵션 — 레버리지와 헤징의 세계",
             "level": "심화", "duration": "10분",
             "concepts": ["선물", "옵션", "레버리지", "헤징"]},
            {"id": "invest-9", "title": "매크로 투자",
             "description": "경제 사이클로 큰 그림 읽기 — 레이 달리오의 원칙",
             "level": "심화", "duration": "10분",
             "concepts": ["경제 사이클", "올웨더 포트폴리오", "인플레이션"]},
            {"id": "invest-10", "title": "세금과 절세 전략",
             "description": "수익을 내도 세금을 내야 한다 — ISA, 연금 계좌 활용법",
             "level": "심화", "duration": "9분",
             "concepts": ["양도소득세", "ISA", "연금저축", "절세"]},
        ],
    },
    "psych": {
        "title": "심리학",
        "emoji": "🧬",
        "color": "#EC4899",
        "description": "인간의 마음과 행동을 과학으로 이해하기",
        "topic_names": ["심리학"],
        "chapters": [
            {"id": "psych-1", "title": "인지 편향",
             "description": "우리 뇌가 만들어내는 착각들",
             "level": "입문", "duration": "7분",
             "concepts": ["확증 편향", "가용성 편향", "앵커링"]},
            {"id": "psych-2", "title": "행동경제학",
             "description": "넛지, 손실 회피 — 합리적이지 않은 우리",
             "level": "기본", "duration": "8분",
             "concepts": ["넛지", "손실 회피", "현상 유지 편향"]},
            {"id": "psych-3", "title": "성격 심리학",
             "description": "MBTI를 넘어서 — Big Five 모델",
             "level": "기본", "duration": "7분",
             "concepts": ["Big Five", "외향성", "개방성", "성실성"]},
            {"id": "psych-4", "title": "사회 심리학",
             "description": "동조, 복종, 집단 사고의 무서움",
             "level": "심화", "duration": "9분",
             "concepts": ["동조", "복종", "집단 사고", "밀그램 실험"]},
            {"id": "psych-5", "title": "긍정 심리학",
             "description": "행복은 만들 수 있다 — 과학이 말하는 웰빙",
             "level": "심화", "duration": "8분",
             "concepts": ["PERMA", "플로우", "회복탄력성"]},
            {"id": "psych-6", "title": "발달 심리학",
             "description": "아이부터 노인까지 — 인간은 어떻게 성장하는가?",
             "level": "기본", "duration": "8분",
             "concepts": ["애착 이론", "피아제", "에릭슨 발달 단계"]},
            {"id": "psych-7", "title": "이상 심리학",
             "description": "불안, 우울, 강박 — 마음의 병을 과학으로 이해하기",
             "level": "기본", "duration": "9분",
             "concepts": ["DSM-5", "불안장애", "우울증", "인지행동치료"]},
            {"id": "psych-8", "title": "뇌과학과 심리학",
             "description": "마음은 뇌에서 나온다 — 신경과학 기초",
             "level": "심화", "duration": "9분",
             "concepts": ["뉴런", "도파민", "전전두엽", "가소성"]},
            {"id": "psych-9", "title": "관계 심리학",
             "description": "사랑, 우정, 갈등 — 인간 관계의 심리학",
             "level": "심화", "duration": "8분",
             "concepts": ["애착 유형", "갈등 해소", "공감", "비폭력대화"]},
            {"id": "psych-10", "title": "응용 심리학",
             "description": "직장, 마케팅, 협상에서 심리학을 쓰는 법",
             "level": "심화", "duration": "10분",
             "concepts": ["설득 원칙", "점화 효과", "조직 심리학"]},
        ],
    },
    "philosophy": {
        "title": "철학",
        "emoji": "💭",
        "color": "#7C3AED",
        "description": "질문으로 세상을 이해하는 오래된 학문",
        "topic_names": ["철학"],
        "chapters": [
            {"id": "philosophy-1", "title": "소크라테스의 방법론",
             "description": "질문으로 진리를 찾는 법 — 산파술이란?",
             "level": "입문", "duration": "6분",
             "concepts": ["산파술", "무지의 지", "변증법"]},
            {"id": "philosophy-2", "title": "윤리학의 세 갈래",
             "description": "공리주의, 의무론, 덕 윤리학 — 무엇이 옳은가?",
             "level": "기본", "duration": "8분",
             "concepts": ["공리주의", "의무론", "덕 윤리학"]},
            {"id": "philosophy-3", "title": "존재란 무엇인가?",
             "description": "하이데거, 사르트르 — 실존주의 쉽게 이해하기",
             "level": "기본", "duration": "9분",
             "concepts": ["실존주의", "실존은 본질에 앞선다", "불안"]},
            {"id": "philosophy-4", "title": "인식론",
             "description": "우리는 무엇을 알 수 있는가? — 데카르트부터 흄까지",
             "level": "심화", "duration": "10분",
             "concepts": ["합리론", "경험론", "코기토"]},
            {"id": "philosophy-5", "title": "AI 시대의 철학",
             "description": "의식, 자유의지, 책임 — 철학이 던지는 질문들",
             "level": "심화", "duration": "10분",
             "concepts": ["튜링 테스트", "중국어 방 논증", "자유의지"]},
            {"id": "philosophy-6", "title": "정치 철학",
             "description": "민주주의, 자유, 정의 — 사회는 어떻게 구성되어야 할까?",
             "level": "기본", "duration": "9분",
             "concepts": ["사회계약론", "자유주의", "공동체주의", "롤스"]},
            {"id": "philosophy-7", "title": "미학과 예술 철학",
             "description": "아름다움이란 무엇인가? — 칸트부터 현대 미술까지",
             "level": "기본", "duration": "8분",
             "concepts": ["숭고", "예술의 정의", "취미 판단"]},
            {"id": "philosophy-8", "title": "과학 철학",
             "description": "과학은 어떻게 발전하는가? — 패러다임 전환과 반증주의",
             "level": "심화", "duration": "9분",
             "concepts": ["패러다임", "쿤", "포퍼의 반증주의", "과학혁명"]},
            {"id": "philosophy-9", "title": "언어 철학",
             "description": "언어가 사고를 결정한다? — 비트겐슈타인과 언어 게임",
             "level": "심화", "duration": "9분",
             "concepts": ["언어 게임", "의미 이론", "화행 이론"]},
            {"id": "philosophy-10", "title": "현대 철학의 흐름",
             "description": "분석 철학, 현상학, 포스트모더니즘 — 20세기 이후 철학",
             "level": "심화", "duration": "10분",
             "concepts": ["분석 철학", "현상학", "구조주의", "해체"]},
        ],
    },
    "startup": {
        "title": "스타트업",
        "emoji": "🚀",
        "color": "#F97316",
        "description": "아이디어를 비즈니스로 만드는 창업의 원리",
        "topic_names": ["스타트업"],
        "chapters": [
            {"id": "startup-1", "title": "스타트업 vs 일반 기업",
             "description": "차이를 알면 전략이 보인다",
             "level": "입문", "duration": "5분",
             "concepts": ["스타트업", "확장성", "불확실성"]},
            {"id": "startup-2", "title": "Product-Market Fit",
             "description": "사람들이 원하는 걸 만드는 법 — PMF란?",
             "level": "기본", "duration": "8분",
             "concepts": ["PMF", "고객 인터뷰", "페인 포인트"]},
            {"id": "startup-3", "title": "린 스타트업",
             "description": "빠르게 만들고 빠르게 배우는 법 — MVP 전략",
             "level": "기본", "duration": "7분",
             "concepts": ["MVP", "Build-Measure-Learn", "피봇"]},
            {"id": "startup-4", "title": "투자 유치 기초",
             "description": "시드, 시리즈A, VC — 창업자가 알아야 할 투자 언어",
             "level": "심화", "duration": "9분",
             "concepts": ["VC", "엔젤 투자", "밸류에이션", "텀시트"]},
            {"id": "startup-5", "title": "그로스 해킹",
             "description": "적은 예산으로 폭발적 성장을 만드는 원리",
             "level": "심화", "duration": "10분",
             "concepts": ["그로스 해킹", "바이럴 루프", "리텐션"]},
            {"id": "startup-6", "title": "비즈니스 모델 설계",
             "description": "어떻게 돈을 벌까? — 구독, 광고, 마켓플레이스 모델 비교",
             "level": "기본", "duration": "8분",
             "concepts": ["수익 모델", "구독", "마켓플레이스", "SaaS"]},
            {"id": "startup-7", "title": "고객 세그먼테이션과 포지셔닝",
             "description": "누구에게 팔 것인가? — ICP와 포지셔닝 전략",
             "level": "기본", "duration": "8분",
             "concepts": ["ICP", "페르소나", "포지셔닝", "차별화"]},
            {"id": "startup-8", "title": "스타트업 조직 문화",
             "description": "사람이 전략보다 중요한 이유 — 팀 빌딩과 문화",
             "level": "심화", "duration": "9분",
             "concepts": ["팀 빌딩", "OKR", "심리적 안전", "온보딩"]},
            {"id": "startup-9", "title": "글로벌 확장 전략",
             "description": "한국을 넘어서 — 해외 진출의 현실과 전략",
             "level": "심화", "duration": "10분",
             "concepts": ["로컬라이제이션", "GTM 전략", "규제", "문화 차이"]},
            {"id": "startup-10", "title": "실패 케이스 스터디",
             "description": "잘 나가다 망한 스타트업들에서 배우는 교훈",
             "level": "심화", "duration": "10분",
             "concepts": ["번 레이트", "피봇 실패", "공동창업자 갈등", "시장 타이밍"]},
        ],
    },
    "health": {
        "title": "헬스/운동",
        "emoji": "💪",
        "color": "#84CC16",
        "description": "몸을 과학적으로 이해하고 관리하기",
        "topic_names": ["헬스/운동", "헬스", "운동"],
        "chapters": [
            {"id": "health-1", "title": "운동 과학 기초",
             "description": "근육은 어떻게 성장하는가? — 점진적 과부하 원리",
             "level": "입문", "duration": "6분",
             "concepts": ["근비대", "점진적 과부하", "근섬유"]},
            {"id": "health-2", "title": "영양학 핵심",
             "description": "단백질, 탄수화물, 지방 — 언제 얼마나 먹어야 할까?",
             "level": "기본", "duration": "7분",
             "concepts": ["단백질", "탄수화물", "칼로리", "TDEE"]},
            {"id": "health-3", "title": "유산소 vs 무산소",
             "description": "목적에 맞는 운동 선택법",
             "level": "기본", "duration": "6분",
             "concepts": ["유산소 운동", "무산소 운동", "심박수 존"]},
            {"id": "health-4", "title": "수면과 회복",
             "description": "운동만큼 중요한 휴식의 과학",
             "level": "기본", "duration": "7분",
             "concepts": ["수면 주기", "코르티솔", "오버트레이닝"]},
            {"id": "health-5", "title": "운동 습관 만들기",
             "description": "작심삼일을 넘어서 — 행동 설계의 심리학",
             "level": "심화", "duration": "8분",
             "concepts": ["습관 루프", "환경 설계", "작은 시작"]},
            {"id": "health-6", "title": "체성분과 체중 관리",
             "description": "체중 말고 체성분을 봐야 하는 이유",
             "level": "기본", "duration": "7분",
             "concepts": ["체지방률", "근육량", "인바디", "기초대사량"]},
            {"id": "health-7", "title": "스트레스와 건강",
             "description": "만성 스트레스가 몸에 미치는 영향과 관리법",
             "level": "기본", "duration": "7분",
             "concepts": ["코르티솔", "자율신경계", "마음챙김", "HRV"]},
            {"id": "health-8", "title": "스포츠 영양학",
             "description": "운동 전후 언제 뭘 먹어야 할까?",
             "level": "심화", "duration": "8분",
             "concepts": ["글리코겐", "운동 전 식사", "단백질 타이밍", "수화"]},
            {"id": "health-9", "title": "부상 예방과 회복",
             "description": "안 다치는 것이 최고의 운동 — 워밍업과 쿨다운 과학",
             "level": "심화", "duration": "8분",
             "concepts": ["워밍업", "쿨다운", "RICE", "근막 이완"]},
            {"id": "health-10", "title": "나이에 맞는 운동",
             "description": "20대, 40대, 60대 — 각 시기에 맞는 운동 전략",
             "level": "심화", "duration": "9분",
             "concepts": ["근감소증", "노인 운동", "호르몬 변화", "유연성"]},
        ],
    },
    "history": {
        "title": "역사",
        "emoji": "📜",
        "color": "#78716C",
        "description": "과거를 통해 현재와 미래를 읽는 법",
        "topic_names": ["역사"],
        "chapters": [
            {"id": "history-1", "title": "역사를 보는 눈",
             "description": "사료, 해석, 관점 — 역사는 어떻게 만들어지는가?",
             "level": "입문", "duration": "6분",
             "concepts": ["사료", "1차 사료", "역사 해석", "관점"]},
            {"id": "history-2", "title": "문명의 흥망",
             "description": "로마, 당나라, 오스만 — 제국은 왜 무너지는가?",
             "level": "기본", "duration": "8분",
             "concepts": ["제국의 붕괴", "내부 모순", "외부 충격"]},
            {"id": "history-3", "title": "산업혁명",
             "description": "세상을 바꾼 200년 — 기술이 사회를 어떻게 뒤집었나",
             "level": "기본", "duration": "7분",
             "concepts": ["증기기관", "공장제", "도시화", "노동 운동"]},
            {"id": "history-4", "title": "20세기의 비극과 기적",
             "description": "전쟁, 냉전, 그리고 경제 성장의 역설",
             "level": "심화", "duration": "10분",
             "concepts": ["세계대전", "냉전", "탈식민지화", "한강의 기적"]},
            {"id": "history-5", "title": "한국 현대사",
             "description": "압축 성장의 빛과 그림자 — 어떻게 여기까지 왔나?",
             "level": "심화", "duration": "9분",
             "concepts": ["압축 성장", "민주화", "외환위기", "디지털 전환"]},
            {"id": "history-6", "title": "동아시아 문명과 교류",
             "description": "한중일 3국은 어떻게 서로 영향을 주고받았나?",
             "level": "기본", "duration": "8분",
             "concepts": ["실크로드", "한자 문화권", "책봉 체제", "해금령"]},
            {"id": "history-7", "title": "이슬람 황금기",
             "description": "중세 이슬람이 과학과 철학을 어떻게 보존했나?",
             "level": "기본", "duration": "8분",
             "concepts": ["바그다드", "번역 운동", "대수학", "의학"]},
            {"id": "history-8", "title": "식민지배와 독립 운동",
             "description": "제국주의와 저항 — 아시아·아프리카의 독립 이야기",
             "level": "심화", "duration": "9분",
             "concepts": ["식민지배", "민족주의", "독립 운동", "탈식민주의"]},
            {"id": "history-9", "title": "냉전과 프록시 전쟁",
             "description": "미소 대립이 세계 곳곳에서 일으킨 전쟁들",
             "level": "심화", "duration": "9분",
             "concepts": ["냉전", "프록시 전쟁", "쿠바 미사일 위기", "베트남전"]},
            {"id": "history-10", "title": "디지털 혁명과 현재",
             "description": "인터넷, SNS, AI — 기술이 다시 역사를 쓰고 있다",
             "level": "심화", "duration": "9분",
             "concepts": ["닷컴 버블", "소셜 미디어", "플랫폼 경제", "AI 시대"]},
        ],
    },
}

# chapter.py 하위 호환용 — CHAPTERS 형식으로 변환
CHAPTERS = {
    track_id: {
        "title": track["title"],
        "chapters": track["chapters"],
    }
    for track_id, track in CURRICULUM_CATALOG.items()
}
